# Generated by Django 4.2.3 on 2024-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=20)),
                ("slname", models.CharField(max_length=20)),
                ("sadd", models.CharField(max_length=20)),
                ("sgen", models.CharField(max_length=20)),
                ("sstate", models.CharField(max_length=20)),
                ("scity", models.CharField(max_length=20)),
                ("sdob", models.CharField(max_length=20)),
                ("scor", models.CharField(max_length=20)),
                ("semid", models.CharField(max_length=20)),
            ],
        ),
    ]
